- hosts: localhost
  tasks:
    - name: Créer le déploiement Nginx
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: custom-nginx
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: custom-nginx
            template:
              metadata:
                labels:
                  app: custom-nginx
              spec:
                containers:
                - name: nginx
                  image: my-custom-nginx:latest
                  imagePullPolicy: Never # Très important pour K3d !
                  ports:
                  - containerPort: 80
    - name: Créer le service Nginx
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: custom-nginx-service
            namespace: default
          spec:
            type: NodePort
            selector:
              app: custom-nginx
            ports:
              - port: 80
                targetPort: 80